[[section-solution-strategy]]
= Solution Strategy

=== Technology Decisions

==== Backend

* Solid-auth-Client: users will in the end use this library developed by SOLID, which is open source, and free to use.

* solid-file-client: This a library from github that allow the interchange of files with the POD. It will be used to send and recieve the jsons and multimedia content.

* JSON-LD: We will be using this specification of JSON to manage the routes in the POD. As a consequence of picking this format, we are considering the use of LDFlex library.

* GeoJson: It will be used to send the information to the map, as an abstraction layer in case there is a need to change the map.

* Tripledoc: It is a library that we will use to manage data not directly related to routes.

==== Frontend

* Google Maps: We will need a map to show the users the route, we are selecting Google maps because os its simplicity and variaty of entry formats.

* We are considering the use of some Bootstrap templates for making the design more simple and clean.

==== Development Tools

* Visual Studio Code: It is familiar to us and it has an extense amount of helpful plugins.

=== Organizational Decisions

We will try to follow an agile methodology, similar to Scrum, where we will develop user stories and assign them among us. 

For such a purpose we will be using the "project" option in the github. We are now used to develop with a Kanban, due to other subjects in the degree. Therefore, we are implementing one.


