[[section-solution-strategy]]
== Solution Strategy

=== Technology Decisions

==== Backend

* Solid-auth-Client: users will in the end use this library developed by SOLID, which is open source, and free to use. Solves the problems of accessing the pod. 

* solid-file-client: This a library from github that allow the interchange of files with the POD. It will be used to send and recieve the jsons and multimedia content.

* JSON-LD: We will be using this specification of JSON to manage the routes in the POD. We are familiar with json, which will help us to manage the information properly, however it
is not supported yet by the POD.

* Domain model classes: We will create domain objects classes in order to have a common specification for objects used by the different modules of the application. We do not fully take advantage of the javascript objects management but we get a more understandable code.

* Tripledoc: We will use it in order to get the friends of the User.

==== Frontend

* Google Maps: We will need a map to show the users the route, we are selecting Google maps because os its simplicity and variaty of entry formats. However, we need an API key.

* react-bootstrap: we will use this templates for making the design more simple and clean. They are very handy although they can be a bit restrictive in some cases.

* Gpx: we will allow user to import routes in this format, since it is a standard. This will make the application compatible with a lot of files generated by other applications. There are no parsers that really adapt to what we want (we store jsonld) so we will have to implement ours.

==== Development Tools

* Visual Studio Code: It is familiar to us and it has an extense amount of helpful plugins, among them we can point out asciidoctor.

* As an starting point for the implementation, we will be using this library: https://github.com/inrupt/generator-solid-react. We believe that it would be better a better approach for the developing process not to create the project from scratch. It provides many functionality, but it is quite complex and we will need time to fully understand it.

=== Organizational Decisions

We will try to follow an agile methodology, similar to Scrum, where we will develop user stories and assign them among us. 

For such a purpose we will be using the "project" option in the github. We are now used to develop with a Kanban, due to other subjects in the degree. Therefore, we are implementing one.


