[[section-solution-strategy]]
= Solution Strategy

=== Technology Decisions

==== Backend

* Solid-auth-Client: users will in the end use this library developed by SOLID, which is open source, and free to use.

* JSON: We will be using JSON to represent the routes, because we are familiar with it.

*  solid-file-client: This a library from github that allow the interchange of files with the POD. It will be used to send and recieve the jsons and multimedia content.

* GeoJson: It will be used to send the information to the map, as an abstraction layer in case there is a need to change the map.

==== Frontend

* Google Maps: We will need a map to show the users the route, we are selecting Google maps because os its simplicity and variaty of entry formats.

==== Development Tools

* Visual Studio Code: It is familiar to us and it has an extense amount of helpful plugins.

=== Organizational Decisions

We will try to follow an agile methodology, similar to Scrum, where we will develop user stories and assign them among us. 



