[[section-runtime-view]]

== Runtime View

=== Login

1. The user selects it's pod provider
2. The user types it's personal id and password
3. The user clicks the log in button, if success, the application will redirect to the home view, otherwise, the current view will show an error

[plantuml, "loginSequence", png]
----
actor User
User -> Viade: Selects pod provider
User -> Viade: Enters credentials
User -> Viade: Clicks login button
Viade -> Pod: login request
Pod -> Viade: login response
Viade -> User: redirects to the corresponding view
----

=== View routes

1. The user clicks on the "view routes" button of the nav bar
2. Then, the user clicks on the desired route name
3. Finally, the application shows the route on a map with all the needed information.

[plantuml, "viewRoutesSequence", png]
----
actor User
User -> Viade: Clicks on "view routes"
Viade -> Pod: Get all routes request
Pod --> Viade: Get all routes response
Viade --> User: Shows a list with al the routes
User ->  Viade: Clicks on a route name
Viade --> User: Show the route information
----

=== Create a new routes
1. The user clicks on the "Create A Route" button on the navigation bar.
2. The user writes the name and description of the route and creates the points which compose the route using the map at the right, clicking once creates a new point, clicking twice on the same point finishes the route (creating a loop also finishes the route).
3. To finally create the route the user clicks on the "Create Route" button.
[plantuml, "createRouteSequence", png]
----
actor User
User -> Viade: Clicks on "Create A Route"
Viade -> User: Shows the "Create A Route" view 
User --> Viade: Gives a name to the route
User --> Viade: Gives a description to the route
User --> Viade: Creates the route as a list of points
User --> Viade: Submits the route clicking on "Create Route"
Viade --> POD: Uploads the route
----

=== Importing a routes

1. The user clicks the "import route" button
2. The user drags a .gpx file to the view. The routes are now displayed on the map
3. The user clicks the "import" button

[plantuml, "importRoutesSequence", png]
----
actor User
User -> Viade: Clicks on "import routes"
Viade --> User: Show the import routes view
User -> Viade: Drags the .gpx file 
User -> Viade: Clicks on the "import" button
Viade -> Pod: Store routes
Viade --> User: Show a ok message to the user
----

=== Sharing a route with friends
1. The user clicks on the "view routes" button of the navigation bar.
2. The user clicks on the desired route name to be shared.
3. Then the user clicks the "Share Route" button.
4. Finally he writes the WebID of the user or group with which he wants to share the route and clicks the "Share" button.
[plantuml, "shareRouteWithFriendSequence", png]
----
actor User
User -> Viade: Clicks on "view routes"
Viade -> Pod: Get all routes request
Pod --> Viade: Get all routes response
Viade --> User: Shows a list with al the routes
User ->  Viade: Clicks on a route name
Viade --> User: Show the route information
User --> Viade: Clicks on "Share Route"
Viade --> User: Shows the sharing dialog
User --> Viade: Writes the user or group WebID and clicks "Share"
Viade --> POD: Send a notification to the user or group
Viade --> POD: Give read permissions over the route to the user or group
----
=== View shared routes



