[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****

AQUÍ IRÍA LA IMAGEN DEL DIAGRAMA

The user needs his/her device of choice, which must be connected to the Internet; a web browser is required for the user to be able to access the application. Regarding the device, our application can be used with either a computer or a mobile device; however, it's not optimized for the latter so the computer is the preferred option. In the case of the browser, any modern web browser should work fine, although Chrome or Firefox are recommended as they're the ones we have been using during the development.
Our application, Viade, is deployed using GitHub Pages, hosted by GitHub.
A Solid POD is required for using the application. It can be provided by any POD provider, either Inrupt or Solid Community. This POD will be in a server, which can be anywhere in the world.

Motivation::

The motivation behind this deployment structure is that the user can interact with the Solid application to manage his/her routes, which will translate in having to access the user's POD, where the routes will be stored.

Quality and/or Performance Features::

As with any Web application, the performance will be affected by the quality of the network connection and the servers on which the application relies. It's not possible for us to control that.
However, it's worth noting that performance can also be drained by poorly written code; in our application, we strove to make our code with as much quality as possible, so that this would not represent a problem to the final user. 

Mapping of Building Blocks to Infrastructure::

As we mentioned, the main components in the deployment of the application are:
* the user's device (such as his/her PC)
* the browser (in the user's device)
* the web server in which the application is run (whose execution environment is GitHub Pages)
* the application itself
* the user's POD (provided by a POD provider)
* the POD server


=== Infrastructure Level 2

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

==== _<Infrastructure Element 1>_

_<diagram + explanation>_

==== _<Infrastructure Element 2>_

_<diagram + explanation>_

...

==== _<Infrastructure Element n>_

_<diagram + explanation>_
